from django.test import TestCase, Client
from django.urls import reverse
from .models import Student

class RegisterTestCase(TestCase):
    def setUp(self):
        self.client = Client()
        self.register_url = reverse('register')  # replace 'register' with the actual name of your register view

    def test_register_valid_data(self):
        data = {
            'id': 2020018,  # replace with the actual id of the user, or remove this line if id is autogenerated
            'username': 'testuse1r',
            'email': 'testuse1r@example.com',
            'password': 'testpassword123',
        }
        response = self.client.post(self.register_url, data)
        self.assertEqual(response.status_code, 200)
        self.assertEqual(Student.objects.count(), 1)
        self.assertEqual(Student.objects.get().username, 'testuse1r')

    def test_register_invalid_data(self):
        data = {
            'username': '',  # empty username
            'email': 'testuse1r@example.com',
            'password': 'testpassword123'
        }
        response = self.client.post(self.register_url, data)
        self.assertEqual(response.status_code, 400)  # expecting a bad request status
        self.assertEqual(Student.objects.count(), 0)  # no new user should be created