# Generated by Django 5.0.8 on 2024-09-23 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='student_number'),
        ),
    ]
