# Generated by Django 5.0.8 on 2024-08-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='tags',
            new_name='interests',
        ),
    ]
