# Generated by Django 5.0.8 on 2024-09-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_number',
        ),
    ]
