# Generated by Django 5.0.8 on 2024-10-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0002_remove_reports_resolved_at_alter_reports_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
