# Generated by Django 5.0.8 on 2024-08-31 14:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0002_rename_tags_student_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
