# Generated by Django 5.0.8 on 2024-11-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0002_user_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_rejected',
            field=models.BooleanField(null=True),
        ),
    ]
