# Generated by Django 5.0.8 on 2024-10-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0002_membership_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='owned_by',
        ),
    ]
