# Generated by Django 5.0.8 on 2024-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0003_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='bannerURL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='imgURL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
