# Generated by Django 5.1.1 on 2024-11-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.JSONField(),
        ),
    ]
