# Generated by Django 5.1.1 on 2024-11-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0003_alter_user_is_rejected'),
        ('ss_api', '0004_alter_notification_message'),
    ]

    operations = [
    ]
