# Generated by Django 5.0.8 on 2024-08-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0004_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_form',
            field=models.ImageField(blank=True, null=True, upload_to='reg_forms/'),
        ),
    ]
