# Generated by Django 5.0.8 on 2024-10-27 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0005_alter_membership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='comment_post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ss_api.post'),
        ),
    ]
