# Generated by Django 5.1.1 on 2024-10-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0002_friendship_friendrequest'),
        ('ss_api', '0006_reports_comment_post_id'),
    ]

    operations = [
    ]
