# Generated by Django 5.0.2 on 2024-10-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0007_merge_20241028_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_banner',
            field=models.URLField(blank=True, null=True),
        ),
    ]
