# Generated by Django 5.0.8 on 2024-10-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0009_comment_replies_alter_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replies',
            new_name='replied',
        ),
    ]
