# Generated by Django 5.0.2 on 2024-11-14 22:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0009_membership_created_at_membership_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='privacy',
            field=models.CharField(default='public', max_length=255),
        ),
        migrations.AlterField(
            model_name='community',
            name='keyword',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
