# Generated by Django 5.0.8 on 2024-10-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0010_rename_replies_comment_replied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replied',
            new_name='replies',
        ),
    ]
