# Generated by Django 5.1.1 on 2024-11-26 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss_api', '0012_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_mod_enabled', models.BooleanField(default=True)),
                ('report_threshold', models.PositiveIntegerField(default=5)),
                ('word_filter_enabled', models.BooleanField(default=True)),
                ('banned_words', models.JSONField(default=list)),
                ('new_user_restriction', models.PositiveIntegerField(default=0)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('auto_lock_threshold', models.PositiveIntegerField(default=10)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mod_settings', to='ss_api.community')),
            ],
        ),
    ]
